name: ID_ADDER  
on: [pull_request]

jobs:
  id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      - uses: phoenixorigin/id_script@v0.1
        with:
          files: ${{ steps.files.outputs.all }}
      - run: echo ${{ steps.files.outputs.all }} 
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
