name: ID_ADDER 
on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
          fetch-depth: 0
      - uses: phoenixorigin/id_script@v0.1.11
        with:
          files: ${{ steps.abc.outputs.all }}
      - run: echo "${{ steps.abc.outputs.all }}"
      - name: Push changes to PR branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-commit from GitHub Actions"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
