name: ID_ADDER  
on: [push]

jobs:
  id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      - uses: phoenixorigin/id_script@v0.1.17
        with:
          files: ${{ steps.files.outputs.all }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'actions@github.co'
          commit_message: 'chore: update domains id'
